In [6]:
import numpy as np

numpy.array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)

- object : Objek apa pun yang mengekspos metode antarmuka array mengembalikan array, atau apa pun (bersarang) urutan
- dtype  : type data, opsional
- copy   : Opsional. Secara default (True), objek disalin
- order  : C (baris mayor) atau F (utama kolom) atau A (apa saja) (default)
- subok  : Secara default, array yang dikembalikan dipaksa menjadi array kelas dasar. Jika benar, sub-kelas akan diberikan
- ndimin : Menentukan dimensi minimum dari array yang dihasilkan

In [7]:
# Array 1 dimensi
arr = np.array([1,2,3])

In [8]:
print(arr)

[1 2 3]


In [9]:
arr[2]

np.int64(3)

In [11]:
# Array 2 dimensi
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [12]:
# Memanggil tipe data
print(a.dtype)

int64


In [15]:
# contoh 2 tipe data dengan unicode string
arr_1 = np.array(['rambutan','apel','jeruk'])
print(arr_1.dtype)
arr_1 = np.array(['r','a','j'])
print(arr_1.dtype)

<U8
<U1


In [16]:
#contoh 3 tipe data yang didefinisikan
arr_2 = np.array([1,2,3,4],dtype='S')

print(arr_2)
print(arr_2.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [17]:
#contoh 4 tipe data yang diubah
arrs = np.array([1.1,2.1,3.1])

newarr = arrs.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Membuat array dari existed data (yang sudah ada)

In [18]:
# Konversi menjadi ndarray

x = [1,2,3,4,5]
print(type(x))
x =  np.asarray(x)
print(x.dtype)
print(x)

<class 'list'>
int64
[1 2 3 4 5]


In [19]:
# contoh kedua konversi list menjadi array dengan tipe data yang didefinisikan
x = [1,2,3,4,5]
print(type(x))
x = np.asarray(x,dtype='f')
print(x.dtype)
print(x)

<class 'list'>
float32
[1. 2. 3. 4. 5.]


# Task 1 untuk audience :
- Buat dua variable tuple yang berisi angka
- masukkan dua variable tuple tersebut kedalam variable bertipe data list
- konversi list tersebut menjadi array numpy

In [23]:
x = (1,2)
y = (3,4)
z_list = [x,y]
print(z_list)

z = np.asarray(z_list,dtype='i')
print(z.dtype)
print(z)

[(1, 2), (3, 4)]
int32
[[1 2]
 [3 4]]


In [28]:
# Membuat dataframe dengan data random

z = np.arange(0,2,0.2,dtype='f')
x = np.arange(1,11,1)
y = np.arange(10,20,1)

print(z,x,y)

[0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001] [ 1  2  3  4  5  6  7  8  9 10] [10 11 12 13 14 15 16 17 18 19]


In [29]:
import pandas as pd

pd.DataFrame({'z':z,'x':x,'y':y})

z   x   y
0  0.0   1  10
1  0.2   2  11
2  0.4   3  12
3  0.6   4  13
4  0.8   5  14
5  1.0   6  15
6  1.2   7  16
7  1.4   8  17
8  1.6   9  18
9  1.8  10  19

In [30]:
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
x = np.zeros((5,7))
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [32]:
x = np.full((3,4), 0.7)
print(x)

[[0.7 0.7 0.7 0.7]
 [0.7 0.7 0.7 0.7]
 [0.7 0.7 0.7 0.7]]


In [33]:
x = np.random.rand(5,3)
print(x)

[[0.72617299 0.15148668 0.93100307]
 [0.57133716 0.26724804 0.57700363]
 [0.57695368 0.64375742 0.0454761 ]
 [0.43594419 0.85402641 0.96833627]
 [0.31150258 0.40409191 0.03395175]]


In [34]:
pd.DataFrame(x,columns=['x','y','z'])

x         y         z
0  0.726173  0.151487  0.931003
1  0.571337  0.267248  0.577004
2  0.576954  0.643757  0.045476
3  0.435944  0.854026  0.968336
4  0.311503  0.404092  0.033952