<a href="https://colab.research.google.com/github/Syamabbas/PythonDataScience/blob/main/2_Indexing%20Slicing%20Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Index tunggal, field index
import numpy as np
a = np.arange(10)
print(a)
b = a[5]
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [2]:
a = np.arange(10)
print(a)
s = slice(2,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [3]:
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [4]:
a = np.arange(10)
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [6]:
a = np.arange(10)
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [10]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

print('Slice array dari index')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Slice array dari index
[[3 4 5]
 [4 5 6]]


In [14]:
a = np.array([[1,2,3],
             [3,4,5],
             [4,5,6]])

print('Array kita:')
print(a)
print('\n')

print('item dari kolom kedua:')
print(a[...,1])
print('\n')

print('item dari baris kedua:')
print(a[1,...])
print('\n')

print('item dari kolom 1 dan seterusnya:')
print(a[...,1:])

Array kita:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


item dari kolom kedua:
[2 4 5]


item dari baris kedua:
[3 4 5]


item dari kolom 1 dan seterusnya:
[[2 3]
 [4 5]
 [5 6]]
