<a href="https://colab.research.google.com/github/Syamabbas/PythonDataScience/blob/main/2_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
# Index tunggal, field index
import numpy as np
a = np.arange(10)
print(a)
b = a[5]
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [28]:
del print

# You can now test if the built-in print function is restored
print('Built-in print function is restored!')


Built-in print function is restored!


In [ ]:
a = np.arange(10)
print(a)
s = slice(2,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [ ]:
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [ ]:
a = np.arange(10)
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [ ]:
a = np.arange(10)
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

print('Slice array dari index')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Slice array dari index
[[3 4 5]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3],
             [3,4,5],
             [4,5,6]])

print('Array kita:')
print(a)
print('\n')

print('item dari kolom kedua:')
print(a[...,1])
print('\n')

print('item dari baris kedua:')
print(a[1,...])
print('\n')

print('item dari kolom 1 dan seterusnya:')
print(a[...,1:])

Array kita:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


item dari kolom kedua:
[2 4 5]


item dari baris kedua:
[3 4 5]


item dari kolom 1 dan seterusnya:
[[2 3]
 [4 5]
 [5 6]]


In [ ]:
# Int indexing
x = np.array([[1,2],
              [3,4],
              [5,6]])
y = x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [ ]:
x = np.array([[0,1,2],
              [3,4,5],
              [6,7,8],
              [9,10,11]])

print('array asli')
print(x)
print('\n')

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]

print('Hasil dari index integer')
print(y)

array asli
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Hasil dari index integer
[[ 0  2]
 [ 9 11]]


In [ ]:
x = np.array([[0,1,2],
              [3,4,5],
              [6,7,8],
              [9,10,11]])

print('Array asli:')
print(x)
print('\n')

print('Item yang lebih besar dari 5:')
print(x[x>5])

Array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Item yang lebih besar dari 5:
[ 6  7  8  9 10 11]


In [ ]:
a = np.array([np.nan,1,2,np.nan,3,4,5])
print(a[np.isnan(a)])

[nan nan]


In [ ]:
a = np.array([1,2+6j,3.5+5j])
print(a[~np.iscomplex(a)])

[1.+0.j]


In [ ]:
a = np.arange(8)
print('Array asli:')
print(a)
print('\n')

b = a.reshape(4,2)
print('Array yang telah dimodifikasi')
print(b)

Array asli:
[0 1 2 3 4 5 6 7]


Array yang telah dimodifikasi
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [ ]:
a = np.arange(8).reshape(2,4)

print('Array asli:')
print(a)
print('\n')

print('Array yang telah di flattened:')
print(a.flatten())
print('\n')

print('flattened array dalam F-style ordering:')
print(a.flatten(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


Array yang telah di flattened:
[0 1 2 3 4 5 6 7]


flattened array dalam F-style ordering:
[0 4 1 5 2 6 3 7]


In [ ]:
a = np.arange(8).reshape(2,4)

print('Array asli:')
print(a)
print('\n')

print('Hasil dari fungsi ravel:')
print(a.ravel())
print('\n')

print('Menggunakan ravel function dalam F-style ordering:')
print(a.ravel(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


Hasil dari fungsi ravel:
[0 1 2 3 4 5 6 7]


Menggunakan ravel function dalam F-style ordering:
[0 4 1 5 2 6 3 7]


In [30]:
a = np.arange(12).reshape(3,4)

print('Array asli:')
print(a)
print('\n')

print('Array yang telah di transpos:')
print(np.transpose(a))
print('\n')

print('Array yang telah di transpos dengan .T:')
print(a.T)

Array asli:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array yang telah di transpos:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Array yang telah di transpos dengan .T:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [31]:
# concatenate

a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
print('\n')
b = np.array([[5,6],[7,8]])

print('Array Kedua:')
print(b)
print('\n')

# both the arrays are of same dimensions

print('gabungan dua array di sumbu 0:')
print(np.concatenate((a,b)) )
print('\n')

print('gabungan dua array di sumbu 1:')
print(np.concatenate((a,b),axis = 1))

Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


gabungan dua array di sumbu 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


gabungan dua array di sumbu 1:
[[1 2 5 6]
 [3 4 7 8]]


In [32]:
# Stack
a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
print('\n')
b = np.array([[5,6],[7,8]])

print('Array kedua:')
print(b)
print('\n')

print('Stack dua array pada sumbu 0:')
print(np.stack((a,b),0) )
print('\n')

print('Stack dua array pada sumbu 1:')
print(np.stack((a,b),1))

Array Pertama:
[[1 2]
 [3 4]]


Array kedua:
[[5 6]
 [7 8]]


Stack dua array pada sumbu 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack dua array pada sumbu 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [33]:
# hstack
a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
print('\n')
b = np.array([[5,6],[7,8]])

print('Array Kedua:')
print(b)
print('\n')

print('Horizontal stacking:')
c = np.hstack((a,b))
print(c)
print('\n')

Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]




In [34]:
a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
print('\n')
b = np.array([[5,6],[7,8]])

print('Array Kedua:')
print(b)
print('\n')

print('Vertical stacking:')
c = np.vstack((a,b))
print(c)

Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


Vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
