<a href="https://colab.research.google.com/github/Syamabbas/PythonDataScience/blob/main/2_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Index tunggal, field index
import numpy as np
a = np.arange(10)
print(a)
b = a[5]
print(b)

[0 1 2 3 4 5 6 7 8 9]
5


In [ ]:
del print

# You can now test if the built-in print function is restored
print('Built-in print function is restored!')


Built-in print function is restored!


In [ ]:
a = np.arange(10)
print(a)
s = slice(2,7,2)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [ ]:
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [ ]:
a = np.arange(10)
print(a)
print(a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [ ]:
a = np.arange(10)
print(a)
print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]


In [ ]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

print('Slice array dari index')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Slice array dari index
[[3 4 5]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3],
             [3,4,5],
             [4,5,6]])

print('Array kita:')
print(a)
print('\n')

print('item dari kolom kedua:')
print(a[...,1])
print('\n')

print('item dari baris kedua:')
print(a[1,...])
print('\n')

print('item dari kolom 1 dan seterusnya:')
print(a[...,1:])

Array kita:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


item dari kolom kedua:
[2 4 5]


item dari baris kedua:
[3 4 5]


item dari kolom 1 dan seterusnya:
[[2 3]
 [4 5]
 [5 6]]


In [ ]:
# Int indexing
x = np.array([[1,2],
              [3,4],
              [5,6]])
y = x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [ ]:
x = np.array([[0,1,2],
              [3,4,5],
              [6,7,8],
              [9,10,11]])

print('array asli')
print(x)
print('\n')

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]

print('Hasil dari index integer')
print(y)

array asli
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Hasil dari index integer
[[ 0  2]
 [ 9 11]]


In [ ]:
x = np.array([[0,1,2],
              [3,4,5],
              [6,7,8],
              [9,10,11]])

print('Array asli:')
print(x)
print('\n')

print('Item yang lebih besar dari 5:')
print(x[x>5])

Array asli:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


Item yang lebih besar dari 5:
[ 6  7  8  9 10 11]


In [ ]:
a = np.array([np.nan,1,2,np.nan,3,4,5])
print(a[np.isnan(a)])

[nan nan]


In [ ]:
a = np.array([1,2+6j,3.5+5j])
print(a[~np.iscomplex(a)])

[1.+0.j]


In [ ]:
a = np.arange(8)
print('Array asli:')
print(a)
print('\n')

b = a.reshape(4,2)
print('Array yang telah dimodifikasi')
print(b)

Array asli:
[0 1 2 3 4 5 6 7]


Array yang telah dimodifikasi
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [ ]:
a = np.arange(8).reshape(2,4)

print('Array asli:')
print(a)
print('\n')

print('Array yang telah di flattened:')
print(a.flatten())
print('\n')

print('flattened array dalam F-style ordering:')
print(a.flatten(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


Array yang telah di flattened:
[0 1 2 3 4 5 6 7]


flattened array dalam F-style ordering:
[0 4 1 5 2 6 3 7]


In [ ]:
a = np.arange(8).reshape(2,4)

print('Array asli:')
print(a)
print('\n')

print('Hasil dari fungsi ravel:')
print(a.ravel())
print('\n')

print('Menggunakan ravel function dalam F-style ordering:')
print(a.ravel(order = 'F'))

Array asli:
[[0 1 2 3]
 [4 5 6 7]]


Hasil dari fungsi ravel:
[0 1 2 3 4 5 6 7]


Menggunakan ravel function dalam F-style ordering:
[0 4 1 5 2 6 3 7]


In [ ]:
a = np.arange(12).reshape(3,4)

print('Array asli:')
print(a)
print('\n')

print('Array yang telah di transpos:')
print(np.transpose(a))
print('\n')

print('Array yang telah di transpos dengan .T:')
print(a.T)

Array asli:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Array yang telah di transpos:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


Array yang telah di transpos dengan .T:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
# concatenate

a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
print('\n')
b = np.array([[5,6],[7,8]])

print('Array Kedua:')
print(b)
print('\n')

# both the arrays are of same dimensions

print('gabungan dua array di sumbu 0:')
print(np.concatenate((a,b)) )
print('\n')

print('gabungan dua array di sumbu 1:')
print(np.concatenate((a,b),axis = 1))

Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


gabungan dua array di sumbu 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


gabungan dua array di sumbu 1:
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Stack
a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
print('\n')
b = np.array([[5,6],[7,8]])

print('Array kedua:')
print(b)
print('\n')

print('Stack dua array pada sumbu 0:')
print(np.stack((a,b),0) )
print('\n')

print('Stack dua array pada sumbu 1:')
print(np.stack((a,b),1))

Array Pertama:
[[1 2]
 [3 4]]


Array kedua:
[[5 6]
 [7 8]]


Stack dua array pada sumbu 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Stack dua array pada sumbu 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
# hstack
a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
print('\n')
b = np.array([[5,6],[7,8]])

print('Array Kedua:')
print(b)
print('\n')

print('Horizontal stacking:')
c = np.hstack((a,b))
print(c)
print('\n')

Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]




In [ ]:
a = np.array([[1,2],[3,4]])

print('Array Pertama:')
print(a)
print('\n')
b = np.array([[5,6],[7,8]])

print('Array Kedua:')
print(b)
print('\n')

print('Vertical stacking:')
c = np.vstack((a,b))
print(c)

Array Pertama:
[[1 2]
 [3 4]]


Array Kedua:
[[5 6]
 [7 8]]


Vertical stacking:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
a = np.arange(9)

print('Array pertama:')
print(a)
print('\n')

print('Split array menjadi 3 sub array yang setara')
b = np.split(a,3)
print(b)
print('\n')

print('Split array menjadi 4 sub array yang tidak setara')
b = np.split(a,[4,5])
print(b)

Array pertama:
[0 1 2 3 4 5 6 7 8]


Split array menjadi 3 sub array yang setara
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Split array menjadi 4 sub array yang tidak setara
[array([0, 1, 2, 3]), array([4]), array([5, 6, 7, 8])]


In [ ]:
# Mengubah element array (add/remove)
# Resize
import numpy as np

a = np.array([[1,2,3],
             [4,5,6]])

print('Array asli:')
print(a)
print('\n')

print('Shape array pertama')
print(a.shape)
print('\n')
b = np.resize(a,(3,2))

print('Array kedua:')
print(b)
print('\n')

print('Shape array kedua')
print(b.shape)
print('\n')

print('Resize array kedua:')
b = np.resize(a,(3,3))
print(b)

Array asli:
[[1 2 3]
 [4 5 6]]


Shape array pertama
(2, 3)


Array kedua:
[[1 2]
 [3 4]
 [5 6]]


Shape array kedua
(3, 2)


Resize array kedua:
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [ ]:
# Append
import numpy as np
a = np.array([[1,2,3],
             [4,5,6]]) # Changed 'a' to be a 2D array for demonstration

print('Array Awal')
print(a)
print('\n')

print('Append elements to array (flattened if axis not specified):')
# This operation is fine as it flattens the arrays if dimensions don't match or axis is not specified
print(np.append(a, [7,8,9]))
print('\n')

print('Append elements along axis 0 (appending a row):')
# The appended array for axis=0 must have the same number of columns as 'a'
print(np.append(a, [[7,8,9]],axis = 0))
print('\n')

print('Append elements along axis 1 (appending columns):')
# The appended array for axis=1 must have the same number of rows as 'a'
print(np.append(a, [[5,5,5],
                   [7,8,9]],axis = 1))

Array Awal
[[1 2 3]
 [4 5 6]]


Append elements to array (flattened if axis not specified):
[1 2 3 4 5 6 7 8 9]


Append elements along axis 0 (appending a row):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Append elements along axis 1 (appending columns):
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [22]:
# insert
a = np.array([[1,2],
             [3,4],
             [5,6]])

print('Array pertama:')
print(a)
print('\n')

print('Tanpa parameter yang diberikan:')
print(np.insert(a,3,[11,12]))
print('\n')

print('Dengan parameter axis:')
print(np.insert(a,1,[11],axis = 0))
print('\n')

print('Broadcast sepanjanhg axis 1:')
print(np.insert(a,1,11,axis = 1))

Array pertama:
[[1 2]
 [3 4]
 [5 6]]


Tanpa parameter yang diberikan:
[ 1  2  3 11 12  4  5  6]


Dengan parameter axis:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


Broadcast sepanjanhg axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [23]:
# Delete
a = np.arange(12).reshape(3,4)

print('First array:')
print(a)
print('\n')

print('Tanpa parameter axis maka di flattened sebelum di delete:')
print(np.delete(a,5))
print('\n')

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Tanpa parameter axis maka di flattened sebelum di delete:
[ 0  1  2  3  4  6  7  8  9 10 11]




In [24]:
# Unique element
a = np.array([5,2,6,2,7,5,6,8,2,9])

print('Array pertama')
print(a)
print('\n')

print('Value unik dari array pertama:')
u = np.unique(a)
print(u)
print('\n')

print('Index array:')
u,indices = np.unique(a,return_index = True)
print(indices)
print('\n')

Array pertama
[5 2 6 2 7 5 6 8 2 9]


Value unik dari array pertama:
[2 5 6 7 8 9]


Index array:
[1 0 2 4 7 9]




In [25]:
# Broadcasting Array
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

[ 10  40  90 160]


In [26]:
#contoh 2
a = np.array([[0.0,0.0,0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print('Array pertama:')
print(a)
print('\n')

print('Array kedua:')
print(b)
print('\n')

print('Array pertama + Array kedua')
print(a + b)


Array pertama:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Array kedua:
[1. 2. 3.]


Array pertama + Array kedua
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [41]:
a = np.arange (0,60,5)
a = a.reshape(3,4)
b = np.arange (0,40,10)
b = b.reshape (1,4)

print(a)
print(b)

print(a*b)
print(a-b)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ 0 10 20 30]]
[[   0   50  200  450]
 [   0  250  600 1050]
 [   0  450 1000 1650]]
[[  0  -5 -10 -15]
 [ 20  15  10   5]
 [ 40  35  30  25]]
